/**
 * Major UK National Rail stations with their CRS codes.
 * Used for the station search autocomplete.
 * Add more entries as needed — sorted alphabetically.
 */
export const stations = [
  { name: 'Aberdeen', crs: 'ABD' },
  { name: 'Basingstoke', crs: 'BSK' },
  { name: 'Bath Spa', crs: 'BTH' },
  { name: 'Birmingham International', crs: 'BHI' },
  { name: 'Birmingham Moor Street', crs: 'BMO' },
  { name: 'Birmingham New Street', crs: 'BHM' },
  { name: 'Blackpool North', crs: 'BPN' },
  { name: 'Bournemouth', crs: 'BMH' },
  { name: 'Bradford Forster Square', crs: 'BDQ' },
  { name: 'Bradford Interchange', crs: 'BDI' },
  { name: 'Brighton', crs: 'BTN' },
  { name: 'Bristol Parkway', crs: 'BPW' },
  { name: 'Bristol Temple Meads', crs: 'BRI' },
  { name: 'Cambridge', crs: 'CBG' },
  { name: 'Cardiff Central', crs: 'CDF' },
  { name: 'Carlisle', crs: 'CAR' },
  { name: 'Chelmsford', crs: 'CHM' },
  { name: 'Cheltenham Spa', crs: 'CNM' },
  { name: 'Chester', crs: 'CTR' },
  { name: 'Clapham Junction', crs: 'CLJ' },
  { name: 'Colchester', crs: 'COL' },
  { name: 'Coventry', crs: 'COV' },
  { name: 'Crewe', crs: 'CRE' },
  { name: 'Darlington', crs: 'DAR' },
  { name: 'Derby', crs: 'DBY' },
  { name: 'Didcot Parkway', crs: 'DID' },
  { name: 'Doncaster', crs: 'DON' },
  { name: 'Dundee', crs: 'DEE' },
  { name: 'Durham', crs: 'DHM' },
  { name: 'East Croydon', crs: 'ECR' },
  { name: 'Edinburgh', crs: 'EDB' },
  { name: 'Ely', crs: 'ELY' },
  { name: 'Exeter St Davids', crs: 'EXD' },
  { name: 'Gatwick Airport', crs: 'GTW' },
  { name: 'Glasgow Central', crs: 'GLC' },
  { name: 'Glasgow Queen Street', crs: 'GLQ' },
  { name: 'Gloucester', crs: 'GCR' },
  { name: 'Guildford', crs: 'GLD' },
  { name: 'Halifax', crs: 'HFX' },
  { name: 'Harrogate', crs: 'HGT' },
  { name: 'Hemel Hempstead', crs: 'HML' },
  { name: 'Hitchin', crs: 'HIT' },
  { name: 'Huddersfield', crs: 'HUD' },
  { name: 'Hull', crs: 'HUL' },
  { name: 'Inverness', crs: 'INV' },
  { name: 'Ipswich', crs: 'IPS' },
  { name: 'Lancaster', crs: 'LAN' },
  { name: 'Leeds', crs: 'LDS' },
  { name: 'Leicester', crs: 'LEI' },
  { name: 'Liverpool Lime Street', crs: 'LIV' },
  { name: 'London Blackfriars', crs: 'BFR' },
  { name: 'London Bridge', crs: 'LBG' },
  { name: 'London Cannon Street', crs: 'CST' },
  { name: 'London Charing Cross', crs: 'CHX' },
  { name: 'London Euston', crs: 'EUS' },
  { name: 'London Fenchurch Street', crs: 'FST' },
  { name: "London King's Cross", crs: 'KGX' },
  { name: 'London Liverpool Street', crs: 'LST' },
  { name: 'London Marylebone', crs: 'MYB' },
  { name: 'London Paddington', crs: 'PAD' },
  { name: 'London St Pancras International', crs: 'STP' },
  { name: 'London Victoria', crs: 'VIC' },
  { name: 'London Waterloo', crs: 'WAT' },
  { name: 'Luton', crs: 'LUT' },
  { name: 'Luton Airport Parkway', crs: 'LTN' },
  { name: 'Maidenhead', crs: 'MAI' },
  { name: 'Manchester Airport', crs: 'MIA' },
  { name: 'Manchester Piccadilly', crs: 'MAN' },
  { name: 'Manchester Victoria', crs: 'MCV' },
  { name: 'Middlesbrough', crs: 'MBR' },
  { name: 'Milton Keynes Central', crs: 'MKC' },
  { name: 'Newcastle', crs: 'NCL' },
  { name: 'Northampton', crs: 'NMP' },
  { name: 'Norwich', crs: 'NRW' },
  { name: 'Nottingham', crs: 'NOT' },
  { name: 'Oxford', crs: 'OXF' },
  { name: 'Peterborough', crs: 'PBO' },
  { name: 'Plymouth', crs: 'PLY' },
  { name: 'Portsmouth & Southsea', crs: 'PMS' },
  { name: 'Portsmouth Harbour', crs: 'PMH' },
  { name: 'Preston', crs: 'PRE' },
  { name: 'Reading', crs: 'RDG' },
  { name: 'Salisbury', crs: 'SAL' },
  { name: 'Sheffield', crs: 'SHF' },
  { name: 'Slough', crs: 'SLO' },
  { name: 'Southampton Central', crs: 'SOU' },
  { name: 'Stansted Airport', crs: 'SSD' },
  { name: 'Stevenage', crs: 'SVG' },
  { name: 'Stirling', crs: 'STG' },
  { name: 'Stoke-on-Trent', crs: 'SOT' },
  { name: 'Stratford', crs: 'SRA' },
  { name: 'Sunderland', crs: 'SUN' },
  { name: 'Surbiton', crs: 'SUR' },
  { name: 'Swansea', crs: 'SWA' },
  { name: 'Swindon', crs: 'SWI' },
  { name: 'Twickenham', crs: 'TWI' },
  { name: 'Wakefield Westgate', crs: 'WKF' },
  { name: 'Watford Junction', crs: 'WFJ' },
  { name: 'Welwyn Garden City', crs: 'WGC' },
  { name: 'Wigan North Western', crs: 'WGN' },
  { name: 'Wimbledon', crs: 'WIM' },
  { name: 'Winchester', crs: 'WIN' },
  { name: 'Woking', crs: 'WOK' },
  { name: 'Wolverhampton', crs: 'WVH' },
  { name: 'York', crs: 'YRK' },
]
